spring.application.name=iot
spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]

server.port=${APP_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/iot_humo}
spring.datasource.username=${DB_USERNAME:iot_user}
spring.datasource.password=${DB_PASSWORD:iot_user}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
